# Generated by Django 4.2.8 on 2025-10-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='loading_responsibility',
            field=models.CharField(choices=[('shipper', 'Yük Sahibi Yükleyecek'), ('carrier', 'Taşıyıcı Yükleyecek'), ('both', 'Birlikte Yüklenecek')], default='shipper', help_text='Yükleme sorumluluğu', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='unloading_responsibility',
            field=models.CharField(choices=[('shipper', 'Yük Sahibi İndirecek'), ('carrier', 'Taşıyıcı İndirecek'), ('both', 'Birlikte İndirilecek')], default='shipper', help_text='İndirme sorumluluğu', max_length=20),
        ),
    ]
