# Generated by Django 4.2.8 on 2025-10-12 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_shipment_loading_responsibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='carrier',
            field=models.ForeignKey(blank=True, help_text='Taşıyıcı profili', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_bids', to='website.userprofile'),
        ),
    ]
