# Generated by Django 4.2.8 on 2025-10-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_bid_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Boy (cm)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Uzunluk (cm)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En (cm)', max_digits=10, null=True),
        ),
    ]
