# Generated by Django 4.2.8 on 2025-10-12 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_shipment_height_shipment_length_shipment_width'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentApproval',
        ),
    ]
