# Generated by Django 4.2.8 on 2025-10-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_shipment_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='volume',
        ),
    ]
