# Generated by Django 4.2.8 on 2025-10-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_volume_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bid',
            name='website_bid_carrier_49e6de_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='website_shi_shipper_2d5194_idx',
        ),
        migrations.RemoveIndex(
            model_name='userdocument',
            name='website_use_firebas_a682e2_idx',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='carrier_uid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='shipper_uid',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='assigned_carrier_uid',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipper_uid',
        ),
        migrations.RemoveField(
            model_name='userdocument',
            name='firebase_uid',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='firebase_uid',
        ),
    ]
