# Generated by Django 4.2.8 on 2025-10-12 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_remove_firebase_uid_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Ödeme tutarı (TRY)', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='Platform komisyonu (TRY)', max_digits=10)),
                ('carrier_amount', models.DecimalField(decimal_places=2, help_text='Taşıyıcıya gidecek tutar (TRY)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ödeme Bekliyor'), ('paid', 'Ödendi'), ('in_transit', 'Taşınıyor'), ('delivered', 'Teslim Edildi'), ('completed', 'Tamamlandı'), ('refunded', 'İade Edildi'), ('disputed', 'İhtilaf')], default='pending', max_length=20)),
                ('payment_method', models.CharField(default='credit_card', help_text='Ödeme yöntemi', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='Sanal POS işlem ID', max_length=255)),
                ('payment_provider', models.CharField(blank=True, help_text='Ödeme sağlayıcı (iyzico, paytr, vb)', max_length=100)),
                ('shipper_confirmed_delivery', models.BooleanField(default=False, help_text='Yük sahibi teslim onayı')),
                ('carrier_confirmed_delivery', models.BooleanField(default=False, help_text='Taşıyıcı teslim onayı')),
                ('shipper_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('carrier_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_transferred', models.BooleanField(default=False, help_text='Admin tarafından transfer edildi mi?')),
                ('admin_transferred_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notları')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Ödeme yapıldığı zaman', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Transfer tamamlandığı zaman', null=True)),
                ('admin_transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_payments', to=settings.AUTH_USER_MODEL)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='website.bid')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='website.userprofile')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='website.shipment')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='website.userprofile')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='website_pay_status_a79c43_idx'), models.Index(fields=['shipper', 'status'], name='website_pay_shipper_4ded44_idx'), models.Index(fields=['carrier', 'status'], name='website_pay_carrier_9d7792_idx')],
            },
        ),
    ]
