# Generated by Django 4.2.8 on 2025-10-13 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_add_payment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='shipper_comment',
        ),
        migrations.AddField(
            model_name='bid',
            name='counter_offer_message',
            field=models.TextField(blank=True, help_text='Karşı teklif mesajı'),
        ),
        migrations.AddField(
            model_name='bid',
            name='counter_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Karşı teklif fiyatı (TRY)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='counter_offered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('withdrawn', 'Geri Çekildi'), ('counter_offered', 'Karşı Teklif Verildi')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BidComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(max_length=255)),
                ('is_shipper', models.BooleanField(default=False, help_text='Yük sahibi mi?')),
                ('comment', models.TextField(help_text='Yorum metni')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Yorum yazarı', on_delete=django.db.models.deletion.CASCADE, related_name='bid_comments', to='website.userprofile')),
                ('bid', models.ForeignKey(help_text='Teklif', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.bid')),
            ],
            options={
                'verbose_name': 'Teklif Yorumu',
                'verbose_name_plural': 'Teklif Yorumları',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['bid', 'created_at'], name='website_bid_bid_id_fe20f1_idx')],
            },
        ),
    ]
