# Generated by Django 4.2.8 on 2025-10-13 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_bid_shipper_comment_bid_counter_offer_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('assigned', 'Atandı'), ('picked_up', 'Yük Toplandı'), ('in_transit', 'Yolda'), ('delivered', 'Teslim Edildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(help_text='Durum', max_length=20)),
                ('status_display', models.CharField(help_text='Durum açıklaması', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Konum (şehir/ilçe)', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, help_text='Ek notlar')),
                ('is_automatic', models.BooleanField(default=False, help_text='Otomatik güncelleme mi?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipment', models.ForeignKey(help_text='İlan', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='website.shipment')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Güncelleyen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.userprofile')),
            ],
            options={
                'verbose_name': 'Takip Kaydı',
                'verbose_name_plural': 'Takip Kayıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shipment', '-created_at'], name='website_shi_shipmen_2859d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Puan (1-5)')),
                ('communication_rating', models.IntegerField(default=5, help_text='İletişim puanı (1-5)')),
                ('professionalism_rating', models.IntegerField(default=5, help_text='Profesyonellik puanı (1-5)')),
                ('punctuality_rating', models.IntegerField(default=5, help_text='Zamanında teslimat puanı (1-5)')),
                ('comment', models.TextField(blank=True, help_text='Yorum (opsiyonel)')),
                ('is_shipper_review', models.BooleanField(default=False, help_text='Yük sahibinin yazdığı değerlendirme mi?')),
                ('is_visible', models.BooleanField(default=True, help_text='Görünür mü?')),
                ('is_flagged', models.BooleanField(default=False, help_text='Şikayet edildi mi?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(help_text='Teklif', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='website.bid')),
                ('reviewed', models.ForeignKey(help_text='Değerlendirilen', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='website.userprofile')),
                ('reviewer', models.ForeignKey(help_text='Değerlendiren', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='website.userprofile')),
                ('shipment', models.ForeignKey(help_text='İlan', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='website.shipment')),
            ],
            options={
                'verbose_name': 'Değerlendirme',
                'verbose_name_plural': 'Değerlendirmeler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reviewed', '-created_at'], name='website_rev_reviewe_b40517_idx'), models.Index(fields=['shipment'], name='website_rev_shipmen_471a2e_idx')],
                'unique_together': {('shipment', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('proof_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_shipper', models.BooleanField(default=False, help_text='Yük sahibi mi?')),
                ('proof_type', models.CharField(choices=[('photo', 'Fotoğraf'), ('signature', 'İmza'), ('document', 'Belge')], default='photo', max_length=20)),
                ('file_url', models.URLField(help_text='Firebase Storage URL veya data URL')),
                ('description', models.TextField(blank=True, help_text='Açıklama')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipment', models.ForeignKey(help_text='İlan', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proofs', to='website.shipment')),
                ('uploaded_by', models.ForeignKey(help_text='Yükleyen', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_proofs', to='website.userprofile')),
            ],
            options={
                'verbose_name': 'Teslimat Kanıtı',
                'verbose_name_plural': 'Teslimat Kanıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shipment', '-created_at'], name='website_del_shipmen_fe864d_idx')],
            },
        ),
    ]
