# Generated by Django 4.2.8 on 2025-10-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_shipment_status_shipmenttracking_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='from_floor',
            field=models.IntegerField(blank=True, help_text='Alış adresi kat numarası', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_has_elevator',
            field=models.BooleanField(blank=True, help_text='Alış adresinde normal asansör var mı?', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_has_freight_elevator',
            field=models.BooleanField(blank=True, help_text='Alış adresinde yük asansörü var mı?', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_room_count',
            field=models.CharField(blank=True, help_text='Alış adresi oda sayısı (2+1, 3+1, vb.)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_floor',
            field=models.IntegerField(blank=True, help_text='Teslimat adresi kat numarası', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_has_elevator',
            field=models.BooleanField(blank=True, help_text='Teslimat adresinde normal asansör var mı?', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_has_freight_elevator',
            field=models.BooleanField(blank=True, help_text='Teslimat adresinde yük asansörü var mı?', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_room_count',
            field=models.CharField(blank=True, help_text='Teslimat adresi oda sayısı (2+1, 3+1, vb.)', max_length=10, null=True),
        ),
    ]
