# Generated by Django 4.2.8 on 2025-10-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('meta_description', models.CharField(blank=True, help_text='SEO için kısa açıklama (max 160 karakter)', max_length=160, verbose_name='Meta Açıklama')),
                ('meta_keywords', models.CharField(blank=True, help_text='Virgülle ayrılmış anahtar kelimeler', max_length=200, verbose_name='Anahtar Kelimeler')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Öne Çıkan Görsel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('view_count', models.IntegerField(default=0, verbose_name='Görüntülenme')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-created_at'],
            },
        ),
    ]
