# Generated by Django 4.2.8 on 2025-10-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında'), ('archived', 'Arşivlendi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
    ]
