version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nakliyenet-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nakliyenet
      POSTGRES_USER: nakliyenet_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nakliyenet_user -d nakliyenet"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ../..
      dockerfile: deploy/digitalocean/Dockerfile
    container_name: nakliyenet-web
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn nakliyenet.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 4 --worker-class gthread

  nginx:
    image: nginx:alpine
    container_name: nakliyenet-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  postgres_data:
